### ISSUE TITLE
"Issueベースの開発”レビュー依頼

### ISSUE THREAD

**Issue by kazukiSaga** [kazukiSaga/anaba#36]
■Webアプリの概要
このWebアプリ「Anaba」は、ユーザーが見つけた穴場スポットを投稿し、他のユーザーと共有できるサービスです。ユーザーは各穴場スポットに対して、写真とコメントを投稿できます。投稿された場所は都道府県やタグで検索可能で、スポットには5段階でおすすめ度や混雑の少なさを評価できます。また、Googleマップとの連携により、登録されたスポットを地図上に表示し、視覚的にスポットを探索できます。このサービスは、コロナ禍や円安による観光地の混雑を避け、まだ知られていない静かな場所でリラックスした時間を過ごしたいユーザーに向けて開発されました。
■ProjectsのURL
(https://github.com/users/kazukiSaga/projects/2/views/1)
■MVPリリースまで
- [ ] rails new
- [ ] デプロイ
- [ ] モデル作成
- [ ] トップページ作成
- [ ] ヘッダー作成
- [ ] ユーザー登録機能
- [ ] ログイン機能
- [ ] スポットの登録機能
- [ ] スポット一覧機能
- [ ] スポット詳細機能
- [ ] スポット編集機能
- [ ] タグ作成機能
- [ ] おすすめ度の5段階評価機能
- [ ] 混雑の少なさの５段階評価機能
- [ ] コメント投稿機能
- [ ] 写真保存機能
- [ ] コメント一覧機能
- [ ] コメンと詳細機能
- [ ] 検索機能
- [ ] インクリメントリサーチでの検索機能
- [ ] MVPリリースレビュー依頼
- [ ] MVPレビュー後修正

■MVP後
- [ ] GoogleAPI連携
- [ ] map表示
- [ ] mapにスポット表示
- [ ] スポットの登録機能mapからスポット詳細へのリンク機能
- [ ] Google Maps JavaScript APIでスポットの緯度、経度情報を取得し保存
- [ ] 動作確認

■MVPレビュー依頼予定日
予定日:2024年 9月 15日

**Comment by Mariko222** [comment]
ご提出ありがとうございます。
以下を参考に、1週間ごとの列を作成し、MVPリリースまでのスケジュール作成をお願いします。
https://github.com/orgs/runteq/projects/7/views/1

**Comment by kazukiSaga** [comment]
修正しました再レビューをお願いします。

**Comment by Mariko222** [comment]
修正いただきありがとうございます。
概ね良いかと思います、LGTMです！
