### ISSUE TITLE
MVPリリースレビュー依頼

### ISSUE THREAD

**Issue by kazukiSaga** [kazukiSaga/anaba#39]
## 各種情報  
サービス名  
Anaba  
サービスURL  
https://anaba-front.vercel.app/  
## READMEレビュー時にMVPリリース時点で実装予定だった機能
* [✔️]ユーザー登録機能
* [✔️]ログイン機能
* [　]写真投稿機能
* [　]コメント投稿機能
* [✔️]スポットの登録（スポット名、住所、説明）
* [　]タグ登録機能
* [✔️]スポットを登録したユーザーのみ、登録したスポットの編集可能（スポット名、住所、説明）
* [✔️]インクリメントサーチでの検索機能（スポット名）
* [✔️]検索機能（都道府県）
* [　]検索機能（タグ）
* [✔️]おすすめ度の 5 段階評価機能
* [✔️]混雑の少なさの 5 段階評価機能

## READMEレビュー時から変更した機能  
スポット編集後にスポット詳細画面に遷移予定であったが、スポット一覧画面へ遷移する設計としました。
卒業認定までの開発スケジュール見積もり面談にて講師と確認をとり、以下の機能をMVP時の実装から本リリース時の実装へ変更しました。  
* タグ登録機能  
* コメント機能   
* 写真投稿機能  
* 検索機能（タグ）
## サービスイメージがわかるようなスクリーンショット等  
[![Image from Gyazo](https://i.gyazo.com/3e2de9130bf9cae9e3b71188dd60e2f2.png)](https://gyazo.com/3e2de9130bf9cae9e3b71188dd60e2f2)

**Comment by kazukiSaga** [comment]
MVPリリースのレビューをお願いします。

**Comment by Tsuchiya2** [comment]
Closed状態になってますね。（Closed状態のものをレビューすることは一般的に無いので対応の上、再提出をお願いいたします。）
