### ISSUE TITLE
MVPリリースレビュー依頼

### ISSUE THREAD

**Issue by kazukiSaga** [kazukiSaga/anaba#41]
## 各種情報 
サービスの概要とMVPで検証する事柄：  
 * ユーザーの登録ができるか
 * ログイン、ログアウトができるか
 * スポットの一覧が表示できるか
 * スポットの一覧画面でスポット名でのインクリメントサーチができるか
 * スポットの一覧画面で都道府県で検索ができるか
 * スポットの詳細画面が表示できるか
 * ログイン後、スポットの投稿ができるか
 * スポットの投稿を編集できるか
 * ユーザーは投稿に対して、おすすめ度と混雑の少なさの評価を数字でつけることができるか
 * ユーザーがスポットに対して評価したおすすめ度と混雑の少なさの平均の数字を、詳細画面で表示できるか
サービス名  
Anaba  
サービスURL  
https://anaba-front.vercel.app/  
## READMEレビュー時にMVPリリース時点で実装予定だった機能
* [✔️]ユーザー登録機能
* [✔️]ログイン機能
* [　]写真投稿機能
* [　]コメント投稿機能
* [✔️]スポットの登録（スポット名、住所、説明）
* [　]タグ登録機能
* [✔️]スポットを登録したユーザーのみ、登録したスポットの編集可能（スポット名、住所、説明）
* [✔️]インクリメントサーチでの検索機能（スポット名）
* [✔️]検索機能（都道府県）
* [　]検索機能（タグ）
* [✔️]おすすめ度の 5 段階評価機能
* [✔️]混雑の少なさの 5 段階評価機能

## READMEレビュー時から変更した機能  
スポット編集後にスポット詳細画面に遷移予定であったが、スポット一覧画面へ遷移する設計としました。
卒業認定までの開発スケジュール見積もり面談にて講師と確認をとり、以下の機能をMVP時の実装から本リリース時の実装へ変更しました。  
* タグ登録機能  
* コメント機能   
* 写真投稿機能  
* 検索機能（タグ）
## サービスイメージがわかるようなスクリーンショット等  
[![Image from Gyazo](https://i.gyazo.com/3e2de9130bf9cae9e3b71188dd60e2f2.png)](https://gyazo.com/3e2de9130bf9cae9e3b71188dd60e2f2)

**Comment by kazukiSaga** [comment]
前回レビュー依頼したissueをclosedからopenにすることができなかったため、issueを別に作り直しました。
MVPリリースが今日までという、急な提出で申し訳ありません。再度レビューをお願いします。


前回までのコメント

・MVPリリースのレビューをお願いします。

・Closed状態になってますね。（Closed状態のものをレビューすることは一般的に無いので対応の上、再提出をお願いいたします。）

**Comment by Tsuchiya2** [comment]
https://github.com/user-attachments/assets/8415881b-a1d5-48a2-8d96-78a51dfa67a3

ログイン操作後、ヘッダーの項目が変わらないのですが、これはちゃんとログインできているのか分からなかったです。（ログイン・未ログインでの違いがあればテキストにて説明をお願いします。）

**Comment by kazukiSaga** [comment]
レビューありがとうございます。
確認したところ、何らかが原因で現状、新規登録・ログイン後にページのリロードを行わないとヘッダーの変更が反映されないようになっているようです。
新規登録、もしくはログイン後リロードしていただければ、機能の確認自体はできるかと思われます。
検索機能はスポット一覧ページから検索できるようになっております。

**Comment by kazukiSaga** [comment]
お疲れ様です。テキストにサービスの概要とMVPで検証する事柄についてが抜けていたので追記しました。
MVPリリースが今日までという、急な提出で申し訳ありません。再度レビューをお願いします。

**Comment by Tsuchiya2** [comment]
機能確認が取れました。LGTMです！
引き続き本リリースに向けて開発頑張ってください。

以下、LGTMを出した方々に共通してお伝えしている内容になります。
（Webアプリを就職活動で活用される方向けの内容になります）

===== 本リリースまでに以下も取り組む =====
□ 独自ドメイン反映
    -> DNSやSSLの対応も必要になるのでアピールになり、URLを書類等に記載するときの見栄えも良くなります。
□ OGP（静的 or 動的）
    -> SNS等でシェアするときの見栄えが良くなります。Webアプリであればどんなアプリでも取り入れられるので対応しておきましょう。
□ RSpec（モデルテスト+システムテスト or モデルテスト+リクエストテスト）
    -> 開発における品質の意識や開発効率の意識の高さをアピールできます。Request Specをメインに最低限各機能に正常にアクセスできるか程度はテストで確認できるようにしておきましょう。
□ CI（GitHubActions）
    -> 実際に開発現場でも使われており、アプリ外で技術のアピールが出来るものです。RSpecと合わせて実装を行いましょう。
□ Rubocopを使ってのリファクタリング
    -> Lintチェックツールは開発現場で広く使われています。コードのLintを整えておくことはチームで開発することを意識するうえでとても大切になるので取り入れておきましょう。

他のプログラミング学習者のWebアプリと異なることをアピールするために、よりインパクトのある機能を複数盛り込むことが重要になってきます。
□ SNSログイン（Google or LINE）
    -> ほとんどのアプリに取り入れられてユーザー体験の向上や技術のアピールにつながるので取り入れましょう。
□ 検索機能のアップデート（オートコンプリート、マルチ検索等）
    -> 特にオートコンプリートは検索体験の向上だけではなくJS系の技術も取り入れていることをアピール出来るので積極的に取り入れましょう。

ユーザー体験という面では以下の項目も大切です。
□ オートログイン
    -> ユーザー登録後に再度ログイン操作を行わせないことでユーザー体験を向上させられます。
□ 使い方説明がある
    -> 初めて訪れたユーザーに呈して使い方の説明があることで体験を向上させられます。
□ レスポンシブ対応
    -> いずれのデバイスでも綺麗にサービスが活用できることで体験が良くなります。
□ 利用規約・プライバシーポリシーを未ログイン状態でも確認できる
    -> 利用規約・プライバシーポリシーがあることで、ちゃんとしたサービスという印象を与えられます。
□ ローディングアニメーション（処理が重い箇所）
    -> 処理が重い箇所に何の対応も無いとユーザーが正しく操作できたのか困惑してしまいます。そうした際はローディングアニメーションを表示させることで体験が向上します。

**Comment by kazukiSaga** [comment]
お忙しい中
レビューありがとうございました。
